# Generated by Django 5.1.2 on 2024-11-20 07:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('relationship_status', models.CharField(choices=[('BF', 'Boyfriend'), ('GF', 'Girlfriend'), ('BESTIE', 'Bestie'), ('BESTFRIEND', 'Best Friend'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=20)),
                ('custom_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('personality', models.CharField(choices=[('INTROVERT', 'Introvert'), ('EXTROVERT', 'Extrovert'), ('AMBIVERT', 'Ambivert')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='verification_photos/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='users.user')),
            ],
        ),
    ]
