# Generated by Django 5.1.2 on 2024-11-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userrelationship_user_userverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userverification',
            name='user',
        ),
    ]
